// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson289f166bDecodeGithubComKexirongMonitorServerModels(in *jlexer.Lexer, out *AlarmSend) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "anchor_point":
			out.AnchorPoint = string(in.String())
		case "list":
			out.List = string(in.String())
		case "type":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Type).UnmarshalText(data))
			}
		case "channel":
			out.Channel = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson289f166bEncodeGithubComKexirongMonitorServerModels(out *jwriter.Writer, in AlarmSend) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"anchor_point\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AnchorPoint))
	}
	{
		const prefix string = ",\"list\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.List))
	}
	{
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.RawText((in.Type).MarshalText())
	}
	{
		const prefix string = ",\"channel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Channel))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AlarmSend) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson289f166bEncodeGithubComKexirongMonitorServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AlarmSend) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson289f166bEncodeGithubComKexirongMonitorServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AlarmSend) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson289f166bDecodeGithubComKexirongMonitorServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AlarmSend) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson289f166bDecodeGithubComKexirongMonitorServerModels(l, v)
}
