// Package models contains the types for schema 'monitor'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"fmt"
	"time"
)

// AlarmQueue represents a row from 'monitor.alarm_event'.
type AlarmEvent struct {
	ID          int64     `json:"id"`           // id
	HostName    string    `json:"host_name"`    // host_name
	AnchorPoint string    `json:"anchor_point"` // anchor_point
	Rule        string    `json:"rule"`         // rule
	Value       float64   `json:"value"`        // value
	Message     string    `json:"message"`      // message
	Level       Level     `json:"level"`        // level
	Stat        int       `json:"stat"`         // stat
	HandleMan   string    `json:"handle_man"`   // handle_man
	CreatedAt   time.Time `json:"created_at"`   // created_at
	UpdatedAt   time.Time `json:"updated_at"`   // updated_at

	// xo fields
	_exists, _deleted bool
}

func (aq *AlarmEvent) String() string {
	return fmt.Sprintf(`
	[%s]
	seq: %d, 
	Time: %s,
	HostName: %s,
	AnchorPoint: %s,
	Value: %g,
	Message: %s`,
		aq.Level, aq.ID, aq.CreatedAt, aq.HostName, aq.AnchorPoint, aq.Value, aq.Message)
}

// Exists determines if the AlarmQueue exists in the database.
func (aq *AlarmEvent) Exists() bool {
	return aq._exists
}

// Deleted provides information if the AlarmQueue has been deleted from the database.
func (aq *AlarmEvent) Deleted() bool {
	return aq._deleted
}

// Insert inserts the AlarmQueue to the database.
func (aq *AlarmEvent) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if aq._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO monitor.alarm_event (` +
		`host_name, anchor_point, rule, value, message, level, stat, handle_man, created_at, updated_at` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, aq.HostName, aq.AnchorPoint, aq.Rule, aq.Value, aq.Message, aq.Level, aq.Stat, aq.HandleMan, aq.CreatedAt, aq.UpdatedAt)
	res, err := db.Exec(sqlstr, aq.HostName, aq.AnchorPoint, aq.Rule, aq.Value, aq.Message, aq.Level, aq.Stat, aq.HandleMan, aq.CreatedAt, aq.UpdatedAt)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	aq.ID = int64(id)
	aq._exists = true

	return nil
}

// Update updates the AlarmQueue in the database.
func (aq *AlarmEvent) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aq._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if aq._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE monitor.alarm_event SET ` +
		`host_name = ?, anchor_point = ?, rule = ?, value = ?, message = ?, level = ?, stat = ?, handle_man = ?, created_at = ?, updated_at = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, aq.HostName, aq.AnchorPoint, aq.Rule, aq.Value, aq.Message, aq.Level, aq.Stat, aq.HandleMan, aq.CreatedAt, aq.UpdatedAt, aq.ID)
	_, err = db.Exec(sqlstr, aq.HostName, aq.AnchorPoint, aq.Rule, aq.Value, aq.Message, aq.Level, aq.Stat, aq.HandleMan, aq.CreatedAt, aq.UpdatedAt, aq.ID)
	return err
}

// Save saves the AlarmQueue to the database.
func (aq *AlarmEvent) Save(db XODB) error {
	if aq.Exists() {
		return aq.Update(db)
	}

	return aq.Insert(db)
}

// Delete deletes the AlarmQueue from the database.
func (aq *AlarmEvent) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aq._exists {
		return nil
	}

	// if deleted, bail
	if aq._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM monitor.alarm_event WHERE id = ?`

	// run query
	XOLog(sqlstr, aq.ID)
	_, err = db.Exec(sqlstr, aq.ID)
	if err != nil {
		return err
	}

	// set deleted
	aq._deleted = true

	return nil
}

// AlarmQueuesByStat retrieves a row from 'monitor.alarm_event' as a AlarmQueue.
//
// Generated from index 'IDX_AlarmEvent_stat'.
func AlarmQueuesByStat(db XODB, stat int) ([]*AlarmEvent, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, host_name, anchor_point, rule, value, message, level, stat, handle_man, created_at, updated_at ` +
		`FROM monitor.alarm_event ` +
		`WHERE stat = ?`

	// run query
	XOLog(sqlstr, stat)
	q, err := db.Query(sqlstr, stat)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AlarmEvent{}
	for q.Next() {
		aq := AlarmEvent{
			_exists: true,
		}

		// scan
		err = q.Scan(&aq.ID, &aq.HostName, &aq.AnchorPoint, &aq.Rule, &aq.Value, &aq.Message, &aq.Level, &aq.Stat, &aq.HandleMan, &aq.CreatedAt, &aq.UpdatedAt)
		if err != nil {
			return nil, err
		}

		res = append(res, &aq)
	}

	return res, nil
}

// AlarmQueueByID retrieves a row from 'monitor.alarm_event' as a AlarmQueue.
//
// Generated from index 'alarm_event_id_pkey'.
func AlarmQueueByID(db XODB, id int64) (*AlarmEvent, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, host_name, anchor_point, rule, value, message, level, stat, handle_man, created_at, updated_at ` +
		`FROM monitor.alarm_event ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	aq := AlarmEvent{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&aq.ID, &aq.HostName, &aq.AnchorPoint, &aq.Rule, &aq.Value, &aq.Message, &aq.Level, &aq.Stat, &aq.HandleMan, &aq.CreatedAt, &aq.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &aq, nil
}
