// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA4b5396cDecodeGithubComKexirongMonitorServerModels(in *jlexer.Lexer, out *AlarmJudge) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "anchor_point":
			out.AnchorPoint = string(in.String())
		case "express":
			out.Express = string(in.String())
		case "level":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.Level).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA4b5396cEncodeGithubComKexirongMonitorServerModels(out *jwriter.Writer, in AlarmJudge) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"anchor_point\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AnchorPoint))
	}
	{
		const prefix string = ",\"express\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Express))
	}
	{
		const prefix string = ",\"level\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.RawText((in.Level).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AlarmJudge) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA4b5396cEncodeGithubComKexirongMonitorServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AlarmJudge) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA4b5396cEncodeGithubComKexirongMonitorServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AlarmJudge) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA4b5396cDecodeGithubComKexirongMonitorServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AlarmJudge) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA4b5396cDecodeGithubComKexirongMonitorServerModels(l, v)
}
