// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAd760b55DecodeGithubComKexirongMonitorServerModels(in *jlexer.Lexer, out *Plugin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "plugin_name":
			out.PluginName = string(in.String())
		case "plugin_type":
			out.PluginType = string(in.String())
		case "file_name":
			out.FileName = string(in.String())
		case "comment":
			out.Comment = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAd760b55EncodeGithubComKexirongMonitorServerModels(out *jwriter.Writer, in Plugin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"plugin_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PluginName))
	}
	{
		const prefix string = ",\"plugin_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PluginType))
	}
	{
		const prefix string = ",\"file_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FileName))
	}
	{
		const prefix string = ",\"comment\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Comment))
	}
	{
		const prefix string = ",\"created_at\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Plugin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAd760b55EncodeGithubComKexirongMonitorServerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Plugin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAd760b55EncodeGithubComKexirongMonitorServerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Plugin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAd760b55DecodeGithubComKexirongMonitorServerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Plugin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAd760b55DecodeGithubComKexirongMonitorServerModels(l, v)
}
