// Package {{ .Package }} contains the types for schema '{{ schema .Schema }}'.
package {{ .Package }}

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"database/sql/driver"
	"errors"
	"fmt"
	"time"
)

